language: go

go:
  - 1.2
  - 1.3
  - tip

install:
    - go get -t .
    - go get -v code.google.com/p/go.tools/cmd/cover
script:
    - go get -v github.com/FreekKalter/km
    - go test -v -covermode=count -coverprofile=main.cov github.com/FreekKalter/km
    - go test -v -covermode=count -coverprofile=lib.cov  github.com/FreekKalter/km/lib
    - tail -n +2 lib.cov >> main.cov
after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=main.cov -service=travis-ci
