language: go

go:
  - 1.2
  - 1.3
  - tip

install:
    - go get -t .
    - go get -v code.google.com/p/go.tools/cmd/cover
script:
    - go get -v github.com/FreekKalter/km
    - go test -v -covermode=count -coverprofile=profile.cov github.com/FreekKalter/km github.com/FreekKalter/km/lib
after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=profile.cov -service=travis-ci
