language: go

go:
  - 1.2
  - 1.3
  - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get code.google.com/p/go.tools/cmd/cover

before_script:
    - go get -t .

script:
    - $HOME/gopath/bin/goveralls -repotoken nKICtFpZJuPL81AEF3Zuxc4eHihVLFSyj
