#!/bin/bash

set -eo pipefail

export ETCD_PORT=${ETCD_PORT:-4001}
export HOST_IP=${HOST_IP:-172.17.42.1}
export ETCD=$HOST_IP:$ETCD_PORT

iuntil confd -onetime -node $ETCD -config-file /etc/confd/conf.d/km.toml; do
    echo "[km] waiting for confd to create initial km configuration"
    sleep 5
done

# Put a continual polling `confd` process into the background to watch
# for changes every 10 seconds
confd -interval 10 -node $ETCD -config-file /etc/confd/conf.d/km.toml &
echo "[km] confd is now monitoring etcd for changes..."

# Start the km service using the generated config
echo "[km] starting nginx service..."
/go/bin/km  /go/bin/km -config=/config/config.yml -workdir=/go/src/github.com/FreekKalter/km &
